packages:
  - apps/*
  - packages/*

injectWorkspacePackages: true

allowBuilds:
  esbuild: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@expo/cli@57.0.13'
  - '@expo/config-plugins@57.0.7'
  - '@supabase/auth-js@2.112.2'
  - '@supabase/functions-js@2.112.2'
  - '@supabase/postgrest-js@2.112.2'
  - '@supabase/realtime-js@2.112.2'
  - '@supabase/storage-js@2.112.2'
  - '@supabase/supabase-js@2.112.2'
  - babel-preset-expo@57.0.6
  - expo-asset@57.0.9
  - expo-file-system@57.0.2
  - expo-modules-core@57.0.10
  - expo-router@57.0.11
  - expo-symbols@57.0.2
  - expo@57.0.11
  - tsx@4.23.9

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - esbuild
  - sharp
  - supabase
