substitutions:
  _IMAGE_TAG: manual
  _REGION: europe-west3
  _REPOSITORY: vibeshub
  _SERVICE: vibeshub-api

steps:
  - id: build-api
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=docker/api.Dockerfile
      - --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_IMAGE_TAG}
      - .

  - id: push-api
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_IMAGE_TAG}

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_IMAGE_TAG}

options:
  logging: CLOUD_LOGGING_ONLY
